import "../styles/nprogress.css";
import "../styles/globals.css";
import Router from "next/router";
import Head from "next/head";
import nProgress from "nprogress";

//Імпорт з node_modules
import "../node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css";
import "reactjs-popup/dist/index.css";
import "../styles/PopUp.css";

Router.events.on("routeChangeStart", nProgress.start);
Router.events.on("routeChangeError", nProgress.done);
Router.events.on("routeChangeComplete", nProgress.done);

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Voice PNU Room</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
        />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        <meta
          name="author"
          content="Seniv Pavlo, https://github.com/PavloSeniv"
        />
        <meta name="copyright" content="Seniv Pavlo" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
