import Head from "next/head";
import styles from "../styles/Home.module.css";
import Welcome from "../components/loginStep/StepWelcome";
import { Oval } from "react-loader-spinner";
import React, { useState, useEffect } from "react";

export default function Login() {
  const [style, setStyle] = useState({ display: "flex" });

  useEffect(() => {
    setTimeout(function () {
      setStyle({ display: "none" });
    }, 3000);
  }, []);

  return (
    <div className={styles.bg__login}>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
        />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        <meta
          name="author"
          content="Seniv Pavlo, https://github.com/PavloSeniv"
        />
        <meta name="copyright" content="Seniv Pavlo" />
      </Head>
      <main className={styles.main + " " + styles.main__container}>
        <Welcome></Welcome>
        <div style={style} className={styles.loader}>
          <Oval
            ariaLabel="Loading..."
            height={100}
            width={100}
            strokeWidth={5}
            strokeWidthSecondary={2}
            color="#5b75a6"
            secondaryColor="white"
          />
        </div>
      </main>
    </div>
  );
}
